name: test

on:
  push:
    branches: [main]
    paths-ignore: [README.md, "screenshots/**"]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    strategy:
      max-parallel: 3
      matrix:
        os: [macos, ubuntu, windows]
        ruby-version: [3.0, 3.4]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@just
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ${{ matrix.ruby-version }}
      - run: just ci
